debug: false

monsters:
  # How long a monster can be idle before it is removed (in seconds)
  idleAge: 600

  # square radius of chunks around a player that never have despawns
  playerChunkRadius: 1

animals:
  # max animals in a given segment, new spawns over this limit
  # are refused
  maxPerSegment: 30

  # chunks per segment: value is squared to represent square size
  # Examples:
  #   0 = 1 chunk 
  #   1 = 9 chunks (3x3 square, ie. tic-tac-toe)
  #   2 = 25 chunks (5x5 square)
  chunkSegmentSize: 1

# set to true to require a player to damage a mob in order
# for the mob to drop items/XP.
playerDamageRequiredForDrops: true

antigrinder:
  enabled: true

antifarm:
